DEBUG: false
DB_CONNECTION: mysql
DB_HOST: localhost
DB_PORT: 3306
DB_DATABASE:
DB_USERNAME:
DB_PASSWORD:
APP_TIMEZONE: UTC
APP_URL: http://localhost
APP_PORT: 8000
PRODUCT_POLL_INTERVAL: 5
ORDER_POLL_INTERVAL: 3
DISCORD_WEBHOOK_URL:
