name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: UI (Version ${{ matrix.node-version }})
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
    - uses: actions/checkout@v5
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build

  build-go:
    name: Go Build
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.1
    - name: Install dependencies
      run: |
        cd API
        go mod download
    - name: Build test
      run: |
        cd API
        go build -v ./...
