name: Pint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pint:
    name: Run Pint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, gd, pdo, openssl, curl, fileinfo,  intl
          tools: composer

      - name: Install Dependencies
        run: composer install --optimize-autoloader

      - name: Run Pint
        run: vendor/bin/pint --test
