name: Python

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Python Install Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: |
          cd API/python-src
          pip install -r requirements.txt
